Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2024-09, with the labels that each got.

#518 fix: 采集任务提前返回问题修复
  pkg/bk-monitor-worker/internal/clustermetrics/es/es.go
Labels: bug, notapd, fix

#520 feat: [bmw] profile 数据支持上报到监控平台
  pkg/bk-monitor-worker/config/apm_config.go
  pkg/bk-monitor-worker/internal/apm/pre_calculate/metrics.go
  pkg/bk-monitor-worker/internal/apm/pre_calculate/pre_calculate.go
Labels: notapd, feat

#521 feat: flow 指标增加 http、rpc 状态码维度 --story=119575812
  pkg/bk-monitor-worker/internal/apm/pre_calculate/window/metrics_processor.go
Labels: fix

#542 feat: 拨测配置模板支持拨测组维度注入 --story=119726599 #541
  pkg/bkmonitorbeat/script/generate_support_files/write_http_conf_tpl.sh
  pkg/bkmonitorbeat/script/generate_support_files/write_tcp_conf_tpl.sh
  pkg/bkmonitorbeat/script/generate_support_files/write_udp_conf_tpl.sh
  pkg/bkmonitorbeat/support-files/templates/freebsd/x86_64/etc/bkmonitorbeat_http.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/freebsd/x86_64/etc/bkmonitorbeat_tcp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/freebsd/x86_64/etc/bkmonitorbeat_udp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/aarch64/etc/bkmonitorbeat_http.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/aarch64/etc/bkmonitorbeat_tcp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/aarch64/etc/bkmonitorbeat_udp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86/etc/bkmonitorbeat_http.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86/etc/bkmonitorbeat_tcp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86/etc/bkmonitorbeat_udp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86_64/etc/bkmonitorbeat_http.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86_64/etc/bkmonitorbeat_tcp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86_64/etc/bkmonitorbeat_udp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86/etc/bkmonitorbeat_http.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86/etc/bkmonitorbeat_tcp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86/etc/bkmonitorbeat_udp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86_64/etc/bkmonitorbeat_http.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86_64/etc/bkmonitorbeat_tcp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86_64/etc/bkmonitorbeat_udp.conf.tpl
Labels: feat
