Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2024-01, with the labels that each got.

#133 fix: 系统事件时间错误问题处理
  pkg/transfer/template/etl/gse_event/custom_string.go
  pkg/transfer/template/etl/gse_event/define.go
  pkg/transfer/template/etl/gse_event/system.go
  pkg/transfer/template/etl/gse_event/system_test.go
Labels: bug, notapd

#135 optimize: unifyquery relation 查询优化
  pkg/unify-query/cmdb/cmdb.go
  pkg/unify-query/cmdb/struct.go
  pkg/unify-query/cmdb/v1beta1/config.go
  pkg/unify-query/cmdb/v1beta1/v1beta1.go
  pkg/unify-query/cmdb/v1beta1/v1beta1_test.go
  pkg/unify-query/service/http/api/api.go
  pkg/unify-query/service/http/api/hook.go
  pkg/unify-query/service/http/api/register.go
  pkg/unify-query/service/http/api/settings.go
Labels: notapd

#130 feat: 增加系统事件清洗日志，调整指标记录判断
  pkg/transfer/template/etl/gse_event/define.go
  pkg/transfer/template/etl/gse_event/system.go
Labels: enhancement, notapd, feat

#118 feat: collector支持fta事件接收
  pkg/collector/controller/register.go
  pkg/collector/define/record.go
  pkg/collector/example/example.yml
  pkg/collector/example/fta/go.mod
  pkg/collector/example/fta/main.go
  pkg/collector/exporter/converter/converter.go
  pkg/collector/exporter/converter/fta.go
  pkg/collector/exporter/converter/fta_test.go
  pkg/collector/exporter/queue/batch.go
  pkg/collector/processor/tokenchecker/factory.go
  pkg/collector/processor/tokenchecker/factory_test.go
  pkg/collector/receiver/config.go
  pkg/collector/receiver/fta/http.go
  pkg/collector/receiver/fta/http_test.go
  pkg/collector/receiver/receiver.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-example
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector.conf
Labels: kind/feat, notapd

#100 unify-query conditions 查询优化
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/structured/condition.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/query/structured/space.go
  pkg/unify-query/query/structured/utils.go
  pkg/unify-query/query/structured/utils_test.go
  pkg/unify-query/service/http/handler_test.go
  pkg/unify-query/tsdb/influxdb/instance.go
Labels: notapd

#158 fix: corefile事件清洗报错问题处理
  pkg/transfer/template/etl/gse_event/define.go
Labels: bug

#165 feat: 更新任务模块配置模块 #115899325
  pkg/bk-monitor-worker/bmw.yaml.tpl
Labels: feat

#98 feat: fta事件清洗逻辑改造，支持配置多组清洗规则
  pkg/transfer/config/metadata_options.go
  pkg/transfer/pipeline/fta.go
  pkg/transfer/template/etl/fta/fta_alert.go
  pkg/transfer/template/etl/fta/fta_alert_test.go
  pkg/transfer/template/etl/fta/fta_flat.go
  pkg/transfer/template/etl/fta/fta_flat_test.go
  pkg/transfer/template/etl/fta/fta_map.go
  pkg/transfer/template/etl/fta/fta_map_test.go
  pkg/transfer/template/etl/fta/fta_rule.go
  pkg/transfer/template/etl/fta/fta_rule_test.go
  pkg/transfer/utils/operate.go
Labels: kind/feat, notapd

#176 feat: 针对数据源刷新功能，异常时，仅记录日志 --story=115959286
  pkg/bk-monitor-worker/cmd/consuldiff.go
  pkg/bk-monitor-worker/http/api.go
  pkg/bk-monitor-worker/internal/apm/pre_calculate/core/meta.go
  pkg/bk-monitor-worker/internal/clustermetrics/influxdb/influxdb.go
  pkg/bk-monitor-worker/internal/metadata/models/common.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/accessvmrecord.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/influxdbclusterinfo.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/influxdbhostinfo.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/influxdbstorage.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/influxdbtaginfo.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/kafkatopicinfo.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/qs_kafkatopicinfo_gen.go
  pkg/bk-monitor-worker/internal/metadata/service/datasource.go
  pkg/bk-monitor-worker/internal/metadata/service/kafkatopicinfo.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup_test.go
  pkg/bk-monitor-worker/internal/metadata/task/async.go
  pkg/bk-monitor-worker/store/consul/consul.go
  pkg/bk-monitor-worker/store/dependentredis/redis.go
  pkg/bk-monitor-worker/store/redis/redis.go
  pkg/bk-monitor-worker/watcher/redis/redis.go
Labels: feat

#180 feat: collector 调整日志打印 --story=115992607
  pkg/collector/VERSION
  pkg/collector/confengine/engine.go
  pkg/collector/pipeline/manager.go
Labels: feat

#181 feat: 修复查询判断异常问题 --story=115997069
  .gtmproject.yaml
  pkg/unify-query/query/promql/utils_test.go
  pkg/unify-query/query/structured/condition.go
  pkg/unify-query/query/structured/condition_test.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
Labels: feat

#183 feat: transfer 支持清洗保留原始字符串 --story=116022455
  pkg/transfer/config/metadata_options.go
  pkg/transfer/etl/transformer.go
Labels: feat

#186 fix: 修复 transfer rtopts 不生效的问题 --bug=119883985
  pkg/transfer/etl/transformer.go
  pkg/transfer/etl/transformer_test.go
  pkg/transfer/template/etl/flat/flat.go
  pkg/transfer/template/etl/formatter/schema_formatter.go
  pkg/transfer/template/etl/fta/fta_alert.go
  pkg/transfer/template/etl/log/log_base.go
  pkg/transfer/template/etl/plugin.go
Labels: fix

#188 fix: 修复 transfer rtops 不生效问题 --bug=119889429
  pkg/transfer/etl/transformer.go
Labels: fix

#189 feat: 更新任务模块版本 --story=116049714
  pkg/bk-monitor-worker/VERSION
Labels: feat

#184 feat: 增加 SkipSpace 功能跳过空间验证 --story=116014600
  pkg/unify-query/metadata/user.go
  pkg/unify-query/query/infos/infos.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/space.go
  pkg/unify-query/service/http/info.go
  pkg/unify-query/service/http/middleware/timer.go
Labels: feat

#190 feat: 移除日志输出 --story=116064561
  pkg/unify-query/query/structured/space.go
Labels: feat
