Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2024-02, with the labels that each got.

#200 feat: 优化 bk_exporter pipeline 处理效率 --story=116195889
  pkg/transfer/define/interface.go
  pkg/transfer/define/payload.go
  pkg/transfer/template/etl/cmdb_injector.go
  pkg/transfer/template/etl/exporter/exporter.go
  pkg/transfer/template/etl/exporter/exporter_test.go
  pkg/transfer/template/etl/group_injector.go
  pkg/transfer/template/pipeline/exporter.go
Labels: feat

#182 feat: 兼容 OT log 获取时间字段 --story=116014927
  pkg/collector/VERSION
  pkg/collector/exporter/converter/logs.go
  pkg/collector/exporter/converter/logs_test.go
  pkg/collector/exporter/converter/metrics_test.go
  pkg/collector/exporter/converter/traces_test.go
  pkg/collector/internal/testkits/first.go
  pkg/collector/receiver/fta/http.go
Labels: feat

#197 feat: 查询支持多时间聚合函数 --story=116138342
  pkg/unify-query/query/structured/method.go
  pkg/unify-query/query/structured/query_promql.go
  pkg/unify-query/service/http/api_test.go
  pkg/unify-query/service/http/handler_test.go
Labels: feat

#201 feat: 增加默认 subquery step 函数 --story=116207653
  pkg/unify-query/query/promql/engine.go
Labels: feat

#195 feat: transfer 调整丢弃空指标配置项 --story=116139750
  pkg/transfer/config/metadata_options.go
  pkg/transfer/kafka/backend.go
Labels: feat

#185 feat: transfer 支持 perforce_meta 特性 --story=116035618
  pkg/transfer/config/metadata_options.go
  pkg/transfer/esb/cc.go
  pkg/transfer/esb/cc_param.go
  pkg/transfer/models/model_info.go
  pkg/transfer/scheduler/cache.go
  pkg/transfer/template/etl/formatter/handler.go
  pkg/transfer/template/etl/formatter/time_series.go
Labels: feat

#210 feat: 优化打 log 方式，修改 conditions 限制和默认 storage --story=116248054
  pkg/unify-query/cmd/root.go
  pkg/unify-query/cmdb/v1beta1/v1beta1_test.go
  pkg/unify-query/curl/curl.go
  pkg/unify-query/curl/mock.go
  pkg/unify-query/log/hook.go
  pkg/unify-query/log/log.go
  pkg/unify-query/log/rotate.go
  pkg/unify-query/log/settings.go
  pkg/unify-query/metadata/reference_test.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/service/http/handler_test.go
  pkg/unify-query/service/http/info.go
  pkg/unify-query/service/http/tsquery_test.go
  pkg/unify-query/service/tsdb/hook.go
  pkg/unify-query/service/tsdb/service.go
  pkg/unify-query/tsdb/bksql/client.go
  pkg/unify-query/tsdb/bksql/client_test.go
  pkg/unify-query/tsdb/influxdb/instance_test.go
  pkg/unify-query/tsdb/prometheus/querier.go
  pkg/unify-query/tsdb/victoriaMetrics/instance_test.go
Labels: feat

#206 feat: 采集器支持上报系统架构 --story=116223031
  pkg/bkmonitorbeat/VERSION
  pkg/bkmonitorbeat/script/generate_support_files/write_root_conf_tpl.sh
  pkg/bkmonitorbeat/support-files/templates/freebsd/x86_64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/aarch64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86_64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86_64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/tasks/static/utils.go
Labels: feat

#205 perf: 优化metric及redis client --story=116215309
  pkg/bk-monitor-worker/http/api.go
  pkg/bk-monitor-worker/internal/clustermetrics/influxdb/influxdb.go
  pkg/bk-monitor-worker/internal/clustermetrics/shipper.go
  pkg/bk-monitor-worker/internal/metadata/models/common.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/accessvmrecord.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/esstorage.go
  pkg/bk-monitor-worker/internal/metadata/service/bcsclusterinfo.go
  pkg/bk-monitor-worker/internal/metadata/service/datasource.go
  pkg/bk-monitor-worker/internal/metadata/service/space.go
  pkg/bk-monitor-worker/internal/metadata/service/space_test.go
  pkg/bk-monitor-worker/internal/metadata/service/spacedatasource.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup_test.go
  pkg/bk-monitor-worker/internal/metadata/task/async.go
  pkg/bk-monitor-worker/metrics/apm.go
  pkg/bk-monitor-worker/metrics/metadata.go
  pkg/bk-monitor-worker/metrics/metrics.go
  pkg/bk-monitor-worker/store/consul/consul.go
  pkg/bk-monitor-worker/store/dependentredis/redis.go
  pkg/bk-monitor-worker/store/dependentredis/redis_test.go
  pkg/bk-monitor-worker/store/redis/redis.go
  pkg/bk-monitor-worker/watcher/redis/redis.go
Labels: GTM, kind/chore

#215 feat: 解冲突及覆盖问题 --story=116269416
  pkg/bk-monitor-worker/internal/metadata/models/storage/esstorage.go
  pkg/bk-monitor-worker/internal/metadata/service/customreportsubscription.go
  pkg/bk-monitor-worker/internal/metadata/service/loggroup.go
  pkg/bk-monitor-worker/internal/metadata/service/pingserversubscriptionconfig.go
  pkg/bk-monitor-worker/internal/metadata/service/space.go
  pkg/bk-monitor-worker/metrics/metrics.go
  pkg/bk-monitor-worker/utils/mocker/confest.go
Labels: feat

#216 fix: 修复指标更新时注册问题 --bug=120718309
  pkg/bk-monitor-worker/metrics/metrics.go
Labels: fix

#204 feat: collector 兼容 trpc-go opentelemetry 指标数据格式转换 --story=116217831
  pkg/collector/VERSION
  pkg/collector/example/subconfig.yml
  pkg/collector/exporter/converter/pushgateway.go
  pkg/collector/exporter/converter/pushgateway_test.go
Labels: feat

#219 fix: fta清洗dedupe_keys需要补充tags前缀
  pkg/transfer/template/etl/fta/fta_alert.go
Labels: bug

#220 test: fta清洗dedupe_keys补充单元测试
  pkg/transfer/template/etl/fta/fta_alert_test.go
  pkg/unify-query/log/log.go
Labels: kind/feat, notapd

#218 feat: 修改 bksql order by 的字段 --story=116296254
  pkg/unify-query/tsdb/bksql/instance.go
Labels: feat

#222 feat: 增加查询校验接口 --story=116308311
  pkg/unify-query/Makefile
  pkg/unify-query/docs/docs.go
  pkg/unify-query/docs/swagger.json
  pkg/unify-query/docs/swagger.yaml
  pkg/unify-query/go.mod
  pkg/unify-query/main.go
  pkg/unify-query/service/http/api.go
  pkg/unify-query/service/http/api/api.go
  pkg/unify-query/service/http/api/response.go
  pkg/unify-query/service/http/check_handler.go
  pkg/unify-query/service/http/handler.go
  pkg/unify-query/service/http/hook.go
  pkg/unify-query/service/http/info.go
  pkg/unify-query/service/http/register_urls.go
  pkg/unify-query/service/http/service.go
  pkg/unify-query/service/http/settings.go
  pkg/unify-query/swagger/swagger.go
  pkg/unify-query/swagger/swagger.json
  pkg/unify-query/swagger/swagger.yaml
Labels: feat
