Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2024-12, with the labels that each got.

#641 feat: 修改 collector 平台配置，增加 fixed_token，给默认上报 APM 应用使用
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-platform.conf.tpl
Labels: notapd, feat

#642 feat: 修改 apm 应用配置，增加对 attributes 字段 as_int 和 as_string 的操作
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-application.conf.tpl
Labels: notapd, feat

#643 fix: 修复手动传token时token没有传递问题 --bug=134869973
  pkg/bk-monitor-worker/utils/remote/prometheus.go
Labels: fix

#651 feat: 【服务】Taf 调用分析 & 自定义指标场景支持 --story=121012625
  pkg/collector/exporter/converter/tars.go
  pkg/collector/exporter/converter/tars_test.go
Labels: feat

#659 feat: 更新 gtm 配置 --story=121136192
  .gtmproject.yaml
Labels: feat, unify-query, datalink

#662 feat: collector 优雅关闭服务 --story=121142839
  pkg/collector/cluster/server.go
  pkg/collector/define/request.go
  pkg/collector/proxy/proxy.go
  pkg/collector/receiver/receiver.go
Labels: feat, datalink

#663 feat: operator 修复 httpsd/polaris sd 更新未正确清理资源的问题 --story=121161946
  pkg/collector/example/parsepprof/go.mod
  pkg/collector/example/parsepprof/go.sum
  pkg/operator/configs/configs.go
  pkg/operator/operator/discover/httpsd/http.go
  pkg/operator/operator/discover/polarissd/polaris.go
  pkg/operator/operator/discover/shareddiscovery/shared_discovery.go
  pkg/operator/operator/operator.go
  pkg/operator/operator/promsd.go
Labels: feat, datalink

#666 feat: 更改 es 查询时间聚合间隔以及增加通配符指定 --story=121191986
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/structured/condition_field.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
Labels: feat, unify-query, datalink

#667 feat: transfer 后端 kafka 支持 sasl 鉴权 --story=121214415
  pkg/transfer/kafka/backend.go
Labels: feat, datalink

#669 feat: operator 支持调整 statefulset worker 扩容重试次数 --story=121252292
  pkg/operator/configs/configs.go
  pkg/operator/operator/secret.go
  pkg/operator/operator/statefulset.go
Labels: feat, datalink

#665 feat: operator 支持上报 helmcharts 版本 --story=121174631
  pkg/collector/example/parsepprof/go.sum
  pkg/operator/common/promfmt/promfmt.go
  pkg/operator/common/promfmt/promfmt_test.go
  pkg/operator/operator/helmcharts/client.go
  pkg/operator/operator/helmcharts/objects.go
  pkg/operator/operator/objectsref/bklogconfig.go
  pkg/operator/operator/objectsref/relation.go
  pkg/operator/operator/objectsref/relation_test.go
  pkg/operator/operator/objectsref/service.go
  pkg/operator/operator/operator.go
  pkg/operator/operator/server.go
Labels: feat, datalink

#668 fix: 修复根据重试次数计算等待时间时得出了maxInt的情况 && 信号量超额释放问题 --bug=135659863
  pkg/bk-monitor-worker/config/config.go
  pkg/bk-monitor-worker/internal/apm/pre_calculate/window/distributive.go
  pkg/bk-monitor-worker/service/scheduler/daemon/maintainer.go
Labels: fix, datalink

#670 feat: operator 支持 dataid 按 name 切割匹配 monitor 资源 --story=121256842
  pkg/operator/apis/monitoring/v1beta1/types.go
  pkg/operator/operator/dataidwatcher/watcher.go
  pkg/operator/operator/dataidwatcher/watcher_test.go
Labels: feat, datalink

#671 feat: BMW: 跨ES查询支持，同步BMW&Metadata模型字段结构，支持ES结果表详情路由刷新 --story=121260282
  pkg/bk-monitor-worker/go.mod
  pkg/bk-monitor-worker/internal/metadata/models/storage/esstorage.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/qs_esstorage_gen.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/qs_storageclusterrecord_gen.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/storageclusterrecord.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
  pkg/bk-monitor-worker/internal/metadata/task/space.go
Labels: feat, datalink, bk-monitor-worker

#664 feat: 优化 bksql 查询逻辑，增加 thedate 条件过滤 --story=121169369
  pkg/unify-query/Makefile
  pkg/unify-query/influxdb/router_mock.go
  pkg/unify-query/internal/function/function.go
  pkg/unify-query/metadata/featureFlag.go
  pkg/unify-query/metadata/featureFlag_test.go
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/bksql/format_test.go
  pkg/unify-query/tsdb/bksql/instance.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
Labels: feat, unify-query, datalink

#674 feat: operator daemonset worker 调度直接屏蔽部分 node --story=121271354
  pkg/operator/common/utils/labels.go
  pkg/operator/common/utils/labels_test.go
  pkg/operator/common/utils/string.go
  pkg/operator/configs/configs.go
  pkg/operator/operator/dataidwatcher/watcher.go
  pkg/operator/operator/metrics.go
  pkg/operator/operator/objectsref/bklogconfig.go
  pkg/operator/operator/objectsref/node.go
  pkg/operator/operator/objectsref/relation.go
  pkg/operator/operator/objectsref/service.go
  pkg/operator/operator/operator.go
  pkg/operator/operator/secret.go
  pkg/operator/operator/server.go
  pkg/operator/operator/target/metric.go
Labels: feat, datalink

#673 feat: BMW: 空间路由支持自定义过滤别名（业务ID别名） --story=121277382
  pkg/bk-monitor-worker/internal/metadata/models/resulttable/qs_resulttable_gen.go
  pkg/bk-monitor-worker/internal/metadata/models/resulttable/resulttable.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/accessvmrecord.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/qs_accessvmrecord_gen.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#677 feat: operator 支持自定义 nodeexporter ext labels --story=121312000
  pkg/operator/common/define/monitor.go
  pkg/operator/common/feature/feature.go
  pkg/operator/common/utils/labels.go
  pkg/operator/operator/discover/base.go
  pkg/operator/operator/discover/httpsd/http.go
  pkg/operator/operator/discover/kubernetesd/kubernetes.go
  pkg/operator/operator/discover/polarissd/polaris.go
  pkg/operator/operator/metrics.go
  pkg/operator/operator/objectsref/controller.go
  pkg/operator/operator/objectsref/node.go
  pkg/operator/operator/objectsref/relabels.go
  pkg/operator/operator/operator.go
  pkg/operator/operator/podmonitor.go
  pkg/operator/operator/promsd.go
  pkg/operator/operator/recorder.go
  pkg/operator/operator/server.go
  pkg/operator/operator/servicemonitor.go
  pkg/operator/operator/target/metric.go
Labels: feat, datalink

#679 feat: 优化 bucket 指标上报的维度 --story=121294466
  pkg/unify-query/metadata/featureFlag.go
  pkg/unify-query/metric/metric.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/tsdb/bksql/client.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/influxdb/instance.go
  pkg/unify-query/tsdb/influxdb/seiesSet.go
  pkg/unify-query/tsdb/offlineDataArchive/seiesSet.go
  pkg/unify-query/tsdb/redis/instance.go
  pkg/unify-query/tsdb/victoriaMetrics/instance.go
Labels: feat, unify-query, datalink
