Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2024-07, with the labels that each got.

#417 minor: 【collector】临时去掉dockerfile中安装的步骤
  pkg/collector/dockerfile/collector/Dockerfile
  pkg/collector/dockerfile/sidecar/Dockerfile
Labels: fix

#400 feat: fta事件处理流程增加日志 --story=118208265
  pkg/transfer/template/etl/fta/fta_alert.go
  pkg/transfer/template/etl/fta/fta_test.go
Labels: feat

#432 feat: run the command (go mod tidy) before packaging
  pkg/collector/control.sh
Labels: notapd, feat

#416 fix: cmdb主机缓存过滤agent信息未及时清理 --bug=126765403
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/base_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/host.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/host_test.go
Labels: fix

#428 chore: 去除无用的fta日志
  pkg/transfer/template/etl/fta/fta_alert.go
Labels: kind/chore

#401 feat: collector 支持 Taf 指标上报 --story=118216976
  .gitignore
  pkg/collector/README.md
  pkg/collector/VERSION
  pkg/collector/controller/register.go
  pkg/collector/define/record.go
  pkg/collector/example/.gitignore
  pkg/collector/example/example.yml
  pkg/collector/example/tars/go.mod
  pkg/collector/example/tars/go.sum
  pkg/collector/example/tars/main.go
  pkg/collector/exporter/converter/converter.go
  pkg/collector/exporter/converter/tars.go
  pkg/collector/exporter/converter/tars_test.go
  pkg/collector/exporter/queue/batch.go
  pkg/collector/go.mod
  pkg/collector/go.sum
  pkg/collector/internal/utils/normalize_test.go
  pkg/collector/internal/utils/utils.go
  pkg/collector/receiver/config.go
  pkg/collector/receiver/receiver.go
  pkg/collector/receiver/receiver_test.go
  pkg/collector/receiver/router.go
  pkg/collector/receiver/tars/tars.go
  pkg/collector/receiver/tars/tars_test.go
  pkg/collector/receiver/tarsprotocol.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-example
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector.conf
  pkg/influxdb-proxy/route/influxdata.go
Labels: feat
