Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2024-03, with the labels that each got.

#225 fix: 修改drop_sampler 模板 --story=116237226
  pkg/collector/processor/sampler/doc.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-application.conf.tpl
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
Labels: notapd, fix

#226 feat: 优化获取consul实例方法 --story=116368599
  pkg/bk-monitor-worker/store/consul/consul.go
Labels: feat

#231 feat: 更新 trace 上报信息 --story=116406750
  pkg/unify-query/cmdb/v1beta1/v1beta1.go
  pkg/unify-query/curl/curl.go
  pkg/unify-query/influxdb/client/client.go
  pkg/unify-query/influxdb/influxdb.go
  pkg/unify-query/influxdb/influxdb_router.go
  pkg/unify-query/influxdb/instance.go
  pkg/unify-query/metadata/featureFlag.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/infos/infos.go
  pkg/unify-query/query/promql/ctx.go
  pkg/unify-query/query/promql/engine.go
  pkg/unify-query/query/promql/querier.go
  pkg/unify-query/query/promql/utils.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/service/http/api.go
  pkg/unify-query/service/http/api/api.go
  pkg/unify-query/service/http/es.go
  pkg/unify-query/service/http/handler.go
  pkg/unify-query/service/http/info.go
  pkg/unify-query/service/http/label_values.go
  pkg/unify-query/service/http/middleware/timer.go
  pkg/unify-query/service/http/promql_query.go
  pkg/unify-query/service/http/tsquery.go
  pkg/unify-query/trace/trace.go
  pkg/unify-query/tsdb/bksql/instance.go
  pkg/unify-query/tsdb/influxdb/instance.go
  pkg/unify-query/tsdb/influxdb/seiesSet.go
  pkg/unify-query/tsdb/influxdb/struct.go
  pkg/unify-query/tsdb/offlineDataArchive/instance.go
  pkg/unify-query/tsdb/offlineDataArchive/seiesSet.go
  pkg/unify-query/tsdb/offlineDataArchive/struct.go
  pkg/unify-query/tsdb/prometheus/instance.go
  pkg/unify-query/tsdb/prometheus/querier.go
  pkg/unify-query/tsdb/victoriaMetrics/instance.go
Labels: feat

#236 feat: collector 修复 pipeline 校验问题 --story=116472461
  pkg/collector/VERSION
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
Labels: feat

#237 feat: collector 调整 proxy 发送批次大小 --story=116474184
  pkg/collector/VERSION
  pkg/collector/exporter/config.go
  pkg/collector/exporter/queue/batch.go
  pkg/collector/receiver/receiver_test.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
Labels: feat

#239 feat: collector 优化 proxy 指标打包逻辑 --story=116477789
  pkg/collector/exporter/config.go
  pkg/collector/exporter/converter/proxy.go
  pkg/collector/exporter/converter/proxy_test.go
  pkg/collector/receiver/receiver_test.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
Labels: feat

#244 feat: 更新版本 --story=116497285
  pkg/bk-monitor-worker/VERSION
Labels: feat

#243 feat: transfer-dbm-v2 --story=116493814
  pkg/transfer/template/etl/formatter/handler.go
  pkg/transfer/template/etl/formatter/handler_test.go
  pkg/transfer/testsuite/mock_define.go
Labels: feat

#245 feat: collector 支持 OT 数据上报从 header 读取 token --story=116471878
  pkg/collector/VERSION
  pkg/collector/define/record.go
  pkg/collector/example/ottracesjson/go.mod
  pkg/collector/example/ottracesjson/main.go
  pkg/collector/example/ottracesjson/traces.json
  pkg/collector/example/parsepprof/go.mod
  pkg/collector/example/parsepprof/go.sum
  pkg/collector/example/parsepprof/main.go
  pkg/collector/example/subconfig.yml
  pkg/collector/exporter/config.go
  pkg/collector/exporter/converter/pingserver.go
  pkg/collector/exporter/converter/profiles.go
  pkg/collector/exporter/converter/profiles_test.go
  pkg/collector/exporter/converter/proxy.go
  pkg/collector/exporter/converter/proxy_test.go
  pkg/collector/exporter/converter/remotewrite.go
  pkg/collector/exporter/queue/batch_test.go
  pkg/collector/processor/pproftranslator/translator.go
  pkg/collector/processor/tokenchecker/factory.go
  pkg/collector/processor/tokenchecker/factory_test.go
  pkg/collector/receiver/otlp/http.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
Labels: feat

#240 feat: 更新 bksql conditions 适配问题 --story=116479068
  pkg/unify-query/cmdb/v1beta1/v1beta1.go
  pkg/unify-query/consul/tsdb.go
  pkg/unify-query/query/structured/condition_field.go
  pkg/unify-query/query/structured/query_promql_test.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/service/http/check_handler.go
  pkg/unify-query/service/http/handler.go
  pkg/unify-query/service/http/handler_test.go
  pkg/unify-query/tsdb/bksql/instance.go
  pkg/unify-query/tsdb/redis/instance.go
  pkg/unify-query/tsdb/victoriaMetrics/instance.go
Labels: feat

#251 feat: 增加 bksql 查询指标打点 --story=116536911
  pkg/unify-query/log/log.go
  pkg/unify-query/query/structured/condition_test.go
  pkg/unify-query/tsdb/bksql/instance.go
Labels: feat

#252 feat: 增加 bksql 查询指标打点 --story=116536911
  pkg/unify-query/tsdb/bksql/instance.go
Labels: feat

#256 feat: 更新任务模块版本号 --story=116606624
  pkg/bk-monitor-worker/VERSION
Labels: feat

#258 fix: 修复部分问题 --bug=121920107
  pkg/bk-monitor-worker/VERSION
  pkg/bk-monitor-worker/internal/metadata/models/constants.go
  pkg/bk-monitor-worker/internal/metadata/service/clusterinfo.go
  pkg/bk-monitor-worker/internal/metadata/service/esstorage_test.go
  pkg/bk-monitor-worker/internal/metadata/service/influxdbstorage.go
  pkg/bk-monitor-worker/internal/metadata/service/influxdbstorage_test.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
  pkg/bk-monitor-worker/internal/metadata/task/space.go
Labels: fix

#259 feat: 添加内存缓存 --story=116640791
  pkg/bk-monitor-worker/go.mod
  pkg/bk-monitor-worker/go.sum
  pkg/bk-monitor-worker/store/memcache/ristretto.go
  pkg/bk-monitor-worker/store/memcache/ristretto_test.go
Labels: feat

#253 feat: collector 扩展 tokenkey 获取方式 --story=116586231
  pkg/collector/VERSION
  pkg/collector/processor/sampler/evaluator/statuscode_test.go
  pkg/collector/processor/tokenchecker/config.go
  pkg/collector/processor/tokenchecker/factory.go
  pkg/collector/processor/tokenchecker/factory_test.go
  pkg/collector/receiver/pushgateway/http.go
Labels: feat

#263 fix: 修复组装集群下发资源配置异常 --bug=122052869
  pkg/bk-monitor-worker/go.mod
  pkg/bk-monitor-worker/internal/metadata/service/bcsclusterinfo.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
  pkg/bk-monitor-worker/internal/metadata/task/config_refresh.go
  pkg/bk-monitor-worker/internal/metadata/task/space.go
  pkg/bk-monitor-worker/service/scheduler/periodic/periodic.go
  pkg/bk-monitor-worker/store/memcache/ristretto.go
  pkg/bk-monitor-worker/store/memcache/ristretto_test.go
Labels: fix

#266 feat: collector OT receiver 处理 tenantKey --story=116702353
  pkg/collector/VERSION
  pkg/collector/receiver/otlp/http.go
Labels: feat

#269 feat: collector GRPC 支持从 header 中提取 token --story=116705557
  pkg/collector/define/record.go
  pkg/collector/receiver/fta/http.go
  pkg/collector/receiver/otlp/grpc.go
  pkg/collector/receiver/otlp/http.go
  pkg/collector/receiver/pushgateway/http.go
  pkg/collector/receiver/remotewrite/http.go
Labels: feat

#270 feat: collector GRPC logs/metrics 提取 header --story=116706303
  pkg/collector/receiver/otlp/grpc.go
Labels: feat

#271 fix: collector 修复 token 默认解析顺序问题 --story=116726298
  pkg/collector/VERSION
  pkg/collector/processor/tokenchecker/factory.go
  pkg/collector/processor/tokenchecker/factory_test.go
  pkg/collector/receiver/fta/http_test.go
Labels: feat

#272 feat: 优化底层日志级别 --story=116720038
  pkg/bk-monitor-worker/broker/redis/redis.go
  pkg/bk-monitor-worker/common/constants.go
  pkg/bk-monitor-worker/http/api.go
  pkg/bk-monitor-worker/http/constants.go
  pkg/bk-monitor-worker/http/daemon.go
  pkg/bk-monitor-worker/http/http.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/clusterinfo.go
  pkg/bk-monitor-worker/metrics/metrics.go
  pkg/bk-monitor-worker/processor/processor.go
  pkg/bk-monitor-worker/store/redis/redis.go
  pkg/bk-monitor-worker/worker/client.go
  pkg/bk-monitor-worker/worker/scheduler.go
Labels: feat
