Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2025-04, with the labels that each got.

#732 feat: es 聚合 missing 兼容 int 类型的字段 --story=122704186
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/prometheus/merge_series_test.go
  pkg/unify-query/tsdb/prometheus/querier.go
Labels: feat, datalink

#737 feat: relation api 支持并发查询 --story=122852024
  pkg/unify-query/bkapi/bkapi_test.go
  pkg/unify-query/cmdb/cmdb.go
  pkg/unify-query/cmdb/v1beta1/v1beta1.go
  pkg/unify-query/mock/handler.go
  pkg/unify-query/service/http/api/api.go
  pkg/unify-query/service/http/api/hook.go
  pkg/unify-query/service/http/api/settings.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
  pkg/unify-query/tsdb/elasticsearch/query_string_test.go
Labels: feat, datalink

#728 feat: 针对 ot metrics 数据的 histogram 类型补充 min/max 指标
  pkg/collector/exporter/converter/metrics.go
  pkg/collector/exporter/converter/metrics_test.go
Labels: notapd, feat

#734 feat: BMW: 空间-RT路由支持根据空间类型+结果表ID自定义过滤条件关键字 --story=122729312
  pkg/bk-monitor-worker/internal/metadata/models/space/qs_spacetypetoresulttablefilteralias_gen.go
  pkg/bk-monitor-worker/internal/metadata/models/space/spacetypetoresulttablefilteralias.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#723 feat: collector 识别 proxy 代理 IP --story=122517814
  pkg/collector/VERSION
  pkg/collector/internal/utils/utils.go
  pkg/collector/internal/utils/utils_test.go
  pkg/collector/proxy/http.go
  pkg/collector/receiver/beat/http.go
  pkg/collector/receiver/fta/http.go
  pkg/collector/receiver/jaeger/http.go
  pkg/collector/receiver/otlp/http.go
  pkg/collector/receiver/pushgateway/http.go
  pkg/collector/receiver/pyroscope/http.go
  pkg/collector/receiver/remotewrite/http.go
  pkg/collector/receiver/skywalking/http.go
  pkg/collector/receiver/zipkin/http.go
Labels: feat, datalink

#738 feat: 查询原始数据移除多余字段 --story=123461236
  pkg/unify-query/service/http/handler.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
Labels: feat, datalink

#742 feat: 优化 tagvalues 查询接口，超过一天的使用 labelvalues 查询 --story=123432529
  pkg/unify-query/mock/handler.go
  pkg/unify-query/service/http/api.go
  pkg/unify-query/service/http/handler_test.go
Labels: feat, datalink

#739 feat: transfer cmdb api调用从esb切换到apigw --story=123525819
  pkg/transfer/esb/cc.go
  pkg/transfer/esb/cc_test.go
  pkg/transfer/esb/client.go
  pkg/transfer/esb/client_test.go
  pkg/transfer/esb/hook.go
Labels: feat, datalink

#743 feat: api 查询增加日志输出 --story=123650893
  pkg/unify-query/service/http/api.go
Labels: feat, datalink

#741 feat: bmw cmdb api调用从esb切换到apigw --story=123548445
  pkg/bk-monitor-worker/config/config.go
  pkg/bk-monitor-worker/go.mod
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/base.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/business.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/cmdb_watch.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/cmdb_watch_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/dynamic_group.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/host.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/module.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/set.go
  pkg/bk-monitor-worker/internal/api/client.go
  pkg/bk-monitor-worker/internal/api/cmdb/cmdb.go
  pkg/bk-monitor-worker/internal/api/cmdb/cmdb_test.go
  pkg/bk-monitor-worker/internal/metadata/apiservice/cmdb.go
  pkg/bk-monitor-worker/internal/metadata/service/customreportsubscription.go
  pkg/bk-monitor-worker/internal/metadata/service/space.go
Labels: feat, datalink, bk-monitor-worker

#745 feat: 非时间聚合接口排序问题修改 --story=123667928
  pkg/unify-query/internal/function/merge_series.go
  pkg/unify-query/internal/function/merge_series_test.go
  pkg/unify-query/internal/function/samples.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/prometheus/querier.go
Labels: feat, datalink

#749 feat: 采集器进程采集新增 process_username 维度 --story=123731258
  pkg/bkmonitorbeat/tasks/proccustom/gather.go
  pkg/bkmonitorbeat/tasks/proccustom/perf.go
  pkg/bkmonitorbeat/tasks/proccustom/port.go
Labels: feat, datalink

#751 feat: 修复 relation query 输出结果为空的情况 --story=123777545
  pkg/unify-query/cmdb/struct.go
  pkg/unify-query/service/http/api/api.go
Labels: feat, datalink

#755 fix: 修复 es 查询 qr 为空的问题 --bug=141941944
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
Labels: fix, datalink
