Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2025-05, with the labels that each got.

#747 feat: RESULT_TABLE_DETAIL补充storage_type --story=123718421
  pkg/bk-monitor-worker/internal/metadata/models/storage/clusterinfo.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/qs_clusterinfo_gen.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#758 feat: es 查询支持前缀模式 --story=123906702
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/structured/condition_field.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
Labels: feat, datalink

#759 feat: es 查询聚合时间适配非毫秒单位 --story=123913773
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/functions.go
  pkg/unify-query/tsdb/elasticsearch/functions_test.go
Labels: feat, datalink

#756 feat: collector 提供 /healthz 接口 --story=123854448
  pkg/collector/VERSION
  pkg/collector/confengine/engine.go
  pkg/collector/define/record.go
  pkg/collector/receiver/receiver.go
Labels: feat, datalink

#712 feat: 日志查询支持doris --story=121933504
  pkg/unify-query/Makefile
  pkg/unify-query/influxdb/router_mock.go
  pkg/unify-query/influxdb/router_test.go
  pkg/unify-query/internal/json/custom.go
  pkg/unify-query/internal/json/custom_test.go
  pkg/unify-query/internal/querystring/expr.go
  pkg/unify-query/internal/querystring/lex.go
  pkg/unify-query/internal/querystring/parser.go
  pkg/unify-query/internal/querystring/parser_test.go
  pkg/unify-query/internal/querystring/querystring.y
  pkg/unify-query/internal/querystring/querystring.y.go
  pkg/unify-query/internal/querystring/y.output
  pkg/unify-query/kvstore/bbolt/bbolt.go
  pkg/unify-query/log/hook.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/mock/handler.go
  pkg/unify-query/query/structured/condition.go
  pkg/unify-query/query/structured/method.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/query/structured/space.go
  pkg/unify-query/query/structured/space_test.go
  pkg/unify-query/service/http/handler.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/service/influxdb/hook.go
  pkg/unify-query/service/influxdb/service.go
  pkg/unify-query/service/influxdb/settings.go
  pkg/unify-query/tsdb/bksql/client_test.go
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/bksql/format_test.go
  pkg/unify-query/tsdb/bksql/instance.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/bksql/sql_expr/base.go
  pkg/unify-query/tsdb/bksql/sql_expr/base_test.go
  pkg/unify-query/tsdb/bksql/sql_expr/doris.go
  pkg/unify-query/tsdb/bksql/sql_expr/doris_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/elasticsearch/query_string.go
  pkg/unify-query/tsdb/elasticsearch/query_string_test.go
  pkg/unify-query/tsdb/victoriaMetrics/instance_test.go
Labels: feat, datalink

#763 feat: 全文检索支持前缀匹配 --story=123997480
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/elasticsearch/query_string.go
  pkg/unify-query/tsdb/elasticsearch/query_string_test.go
Labels: feat, datalink

#731 feat: 采集器基础采集指标完善 --story=122623999
  pkg/bkmonitorbeat/VERSION
  pkg/bkmonitorbeat/beater/beater.go
  pkg/bkmonitorbeat/beater/taskfactory/dmesg.go
  pkg/bkmonitorbeat/beater/taskfactory/timesync.go
  pkg/bkmonitorbeat/configs/config.go
  pkg/bkmonitorbeat/configs/dmesg.go
  pkg/bkmonitorbeat/configs/timesync.go
  pkg/bkmonitorbeat/define/task.go
  pkg/bkmonitorbeat/go.mod
  pkg/bkmonitorbeat/go.sum
  pkg/bkmonitorbeat/script/generate_support_files/write_root_conf_tpl.sh
  pkg/bkmonitorbeat/script/gse_package.sh
  pkg/bkmonitorbeat/support-files/templates/linux/aarch64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86_64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86_64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/tasks/basereport/collector/cpu_stat_windows_test.go
  pkg/bkmonitorbeat/tasks/basereport/collector/net.go
  pkg/bkmonitorbeat/tasks/basereport/collector/system.go
  pkg/bkmonitorbeat/tasks/dmesg/event.go
  pkg/bkmonitorbeat/tasks/dmesg/gather.go
  pkg/bkmonitorbeat/tasks/ping/pinger.go
  pkg/bkmonitorbeat/tasks/timesync/client_linux.go
  pkg/bkmonitorbeat/tasks/timesync/client_other.go
  pkg/bkmonitorbeat/tasks/timesync/gather.go
  pkg/operator/configs/configs.go
  pkg/operator/operator/secret.go
  pkg/operator/operator/target/timesync.go
  pkg/transfer/template/etl/basereport/env.go
  pkg/transfer/template/etl/basereport/inode.go
  pkg/transfer/template/etl/basereport/netstat.go
Labels: feat, datalink

#765 feat: bksql 时间区间&聚合方式&字段屏蔽 --story=124026267
  pkg/unify-query/internal/function/function.go
  pkg/unify-query/internal/function/function_test.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/bksql/format_test.go
  pkg/unify-query/tsdb/bksql/instance.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/bksql/sql_expr/base.go
  pkg/unify-query/tsdb/bksql/sql_expr/doris.go
Labels: feat, datalink

#766 fix: icmp配置模板调整，字符串增加双引号避免 no 被识别成 boolean 类型 --bug=142566655
  pkg/bkmonitorbeat/script/generate_support_files/write_icmp_conf_tpl.sh
  pkg/bkmonitorbeat/support-files/templates/freebsd/x86_64/etc/bkmonitorbeat_icmp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/aarch64/etc/bkmonitorbeat_icmp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86/etc/bkmonitorbeat_icmp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86_64/etc/bkmonitorbeat_icmp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86/etc/bkmonitorbeat_icmp.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86_64/etc/bkmonitorbeat_icmp.conf.tpl
Labels: fix, datalink, bkmontiorbeat

#767 feat: bksql 查询保留字段处理 --story=124108241
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/bksql/instance.go
  pkg/unify-query/tsdb/bksql/instance_test.go
Labels: feat, datalink

#781 feat: 修复 codecc 代码扫描 --story=124238995
  pkg/bk-monitor-worker/internal/metadata/apiservice/cmdb.go
  pkg/bk-monitor-worker/internal/metadata/apiservice/monitor.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/base.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/define.go
  pkg/bk-monitor-worker/metrics/slometrics.go
  pkg/bk-monitor-worker/utils/cipher/bkdata_token.go
  pkg/collector/receiver/skywalking/encoder_test.go
  pkg/influxdb-proxy/backend/factory.go
  pkg/libgse/monitoring/report/bkpipe/bkpipe.go
  pkg/libgse/output/otlp/otlp.go
  pkg/transfer/esb/cc.go
  pkg/transfer/models/model_info.go
  pkg/unify-query/query/structured/promql.go
  pkg/utils/http/http.go
Labels: feat, datalink

#782 feat: 修改 codecc 代码扫描问题 --story=124244015
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup.go
  pkg/unify-query/query/structured/query_ts.go
Labels: feat, datalink

#760 feat: bk-monitor-worker 支持多租户 --story=123908495
  .gitignore
  .pre-commit-config.yaml
  pkg/bk-monitor-worker/config/config.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/base.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/base_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/business.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/business_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/cmdb_watch.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/cmdb_watch_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/dynamic_group.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/dynamic_group_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/host.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/host_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/module.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/module_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/relation_builder_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/service_instance.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/service_instance_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/set.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/set_test.go
  pkg/bk-monitor-worker/internal/api/client.go
  pkg/bk-monitor-worker/internal/api/cmdb/cmdb_test.go
  pkg/bk-monitor-worker/internal/api/cmdb/response.go
  pkg/bk-monitor-worker/internal/api/user/response.go
  pkg/bk-monitor-worker/internal/api/user/user.go
  pkg/bk-monitor-worker/internal/api/user/user_test.go
  pkg/bk-monitor-worker/internal/apm/pre_calculate/storage/storage_test.go
  pkg/bk-monitor-worker/internal/metadata/apiservice/cmdb.go
  pkg/bk-monitor-worker/internal/metadata/apiservice/monitor.go
  pkg/bk-monitor-worker/internal/metadata/models/space/space.go
  pkg/bk-monitor-worker/internal/metadata/service/customreportsubscription.go
  pkg/bk-monitor-worker/internal/metadata/service/esstorage_test.go
  pkg/bk-monitor-worker/internal/metadata/service/space.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
  pkg/bk-monitor-worker/internal/tenant/tenant.go
  pkg/bk-monitor-worker/internal/tenant/tenant_test.go
  pkg/bk-monitor-worker/utils/remote/prometheus_test.go
  pkg/bk-monitor-worker/utils/remote/space_reporter_test.go
Labels: feat, datalink, bk-monitor-worker

#796 feat: es querystring 解析规则支持星号 --story=124396702
  pkg/unify-query/internal/querystring/lex.go
  pkg/unify-query/internal/querystring/parser_test.go
  pkg/unify-query/internal/querystring/querystring.y
  pkg/unify-query/internal/querystring/querystring.y.go
  pkg/unify-query/internal/querystring/y.output
  pkg/unify-query/tsdb/bksql/sql_expr/doris_test.go
  pkg/unify-query/tsdb/elasticsearch/query_string.go
  pkg/unify-query/tsdb/elasticsearch/query_string_test.go
Labels: feat, datalink
