Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2025-06, with the labels that each got.

#804 feat: collector 修改 /healthz API 端口 --story=124448076
  pkg/collector/receiver/admin.go
  pkg/collector/receiver/receiver.go
Labels: feat, datalink

#801 feat: apm 预计算支持多租户
  pkg/bk-monitor-worker/internal/apm/pre_calculate/core/meta.go
  pkg/bk-monitor-worker/internal/apm/pre_calculate/window/processor.go
Labels: notapd, feat

#806 feat: codecc 代码修复 --story=124454221
  pkg/bk-monitor-worker/internal/metadata/service/slopush.go
  pkg/bk-monitor-worker/internal/metadata/service/spacedatasource.go
Labels: feat, datalink

#775 feat: 指标关联支持实体扩展信息 --story=124152119
  pkg/operator/operator/objectsref/pod.go
  pkg/operator/operator/objectsref/relabels.go
  pkg/operator/operator/objectsref/relation.go
  pkg/operator/operator/objectsref/relation_test.go
  pkg/operator/operator/server.go
Labels: feat, datalink

#808 feat: es 查询支持别名 --story=124478006
  pkg/unify-query/metadata/const.go
  pkg/unify-query/metadata/feature_flag.go
  pkg/unify-query/metadata/feature_flag_test.go
  pkg/unify-query/metadata/field_format.go
  pkg/unify-query/metadata/field_format_test.go
  pkg/unify-query/metadata/query_params.go
  pkg/unify-query/metadata/query_reference.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/interfaces.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/space.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/influxdb/instance.go
  pkg/utils/router/influxdb/space.go
  pkg/utils/router/influxdb/space_gen.go
Labels: feat, datalink

#810 feat: 查询支持别名模式 --story=124518093
  pkg/unify-query/metadata/field_format.go
  pkg/unify-query/metadata/field_format_test.go
  pkg/unify-query/metadata/query_params.go
  pkg/unify-query/metadata/query_reference.go
  pkg/unify-query/metadata/query_reference_test.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
Labels: feat, datalink

#811 feat: 采集器修复进程采集指标不准确 bug --story=124537888
  pkg/bkmonitorbeat/VERSION
  pkg/bkmonitorbeat/define/proc.go
  pkg/bkmonitorbeat/tasks/processbeat/process/perf.go
  pkg/bkmonitorbeat/tasks/processbeat/process/process.go
Labels: feat, datalink

#820 feat: BMW: 空间路由整体优化,不再使用不同空间类型不同查询别名方案,解决慢查询问题 --story=124772836
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#821 feat: 高亮支持全文检索 --story=124788475
  pkg/unify-query/internal/function/highlight.go
  pkg/unify-query/internal/function/highlight_test.go
  pkg/unify-query/internal/querystring/expr.go
  pkg/unify-query/internal/querystring/label_map.go
  pkg/unify-query/internal/querystring/label_map_test.go
  pkg/unify-query/internal/querystring/lex.go
  pkg/unify-query/internal/querystring/parser.go
  pkg/unify-query/internal/querystring/parser_test.go
  pkg/unify-query/internal/querystring/querystring.y
  pkg/unify-query/internal/querystring/querystring.y.go
  pkg/unify-query/internal/querystring/y.output
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/elasticsearch/query_string.go
  pkg/unify-query/tsdb/elasticsearch/query_string_test.go
  pkg/unify-query/unify-query.yaml
Labels: feat, datalink

#809 feat: BMW: ES查询别名迁移至UnifyQuery路由方案 --story=124518032
  pkg/bk-monitor-worker/internal/metadata/models/resulttable/esfieldqueryaliasoption.go
  pkg/bk-monitor-worker/internal/metadata/models/resulttable/qs_esfieldalias_gen.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#826 fix: bmw cmdb缓存任务上云特殊参数适配 --bug=143618060
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/base.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/business.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/host.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/module.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/set.go
  pkg/bk-monitor-worker/internal/api/cmdb/cmdb.go
Labels: fix, datalink, bk-monitor-worker

#828 feat: query string 解析支持双引号 --story=124982265
  pkg/unify-query/query/structured/query_ts.go
Labels: feat, datalink

#824 feat: collector 支持从 header/metadata 加载用户元数据信息 --story=124916113
  pkg/collector/VERSION
  pkg/collector/define/record.go
  pkg/collector/example/example.yml
  pkg/collector/example/ottraces/main.go
  pkg/collector/internal/tokenparser/tokenparser.go
  pkg/collector/processor/resourcefilter/config.go
  pkg/collector/processor/resourcefilter/doc.go
  pkg/collector/processor/resourcefilter/factory.go
  pkg/collector/processor/resourcefilter/factory_test.go
  pkg/collector/receiver/otlp/grpc.go
  pkg/collector/receiver/otlp/http.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-k8s-main
Labels: feat, datalink

#830 feat: doris 指标适配 object 类型 --story=124998550
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/sql_expr/doris.go
Labels: feat, datalink

#831 feat: 采集器新增 allocated_files 指标 --story=125015185
  pkg/bkmonitorbeat/VERSION
  pkg/bkmonitorbeat/tasks/basereport/collector/env.go
  pkg/bkmonitorbeat/tasks/basereport/collector/env_unix.go
  pkg/collector/control.sh
Labels: feat, datalink

#829 feat: influxdb 适配多指标 + label_replace 用法 --story=124826638
  pkg/unify-query/influxdb/router_mock.go
  pkg/unify-query/internal/function/function.go
  pkg/unify-query/internal/querystring/expr.go
  pkg/unify-query/internal/querystring/parser_test.go
  pkg/unify-query/internal/querystring/querystring.y
  pkg/unify-query/internal/querystring/querystring.y.go
  pkg/unify-query/metadata/query_reference.go
  pkg/unify-query/metadata/query_reference_test.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/mock/handler.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/query/structured/space.go
  pkg/unify-query/query/structured/space_test.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
  pkg/unify-query/tsdb/elasticsearch/query_string_test.go
  pkg/unify-query/tsdb/influxdb/instance.go
  pkg/unify-query/tsdb/influxdb/instance_test.go
  pkg/unify-query/tsdb/influxdb/seiesSet.go
  pkg/unify-query/tsdb/influxdb/struct.go
  pkg/unify-query/tsdb/victoriaMetrics/instance.go
  pkg/utils/router/influxdb/influxdb.go
Labels: feat, datalink

#835 feat: transfer 新增 allocated_files 清洗 --story=125059520
  pkg/transfer/template/etl/basereport/env.go
Labels: feat, datalink

#833 feat: BMW: refresh_bcs_metrics_label 逻辑移除 --story=125056721
  pkg/bk-monitor-worker/internal/metadata/service/bcsclusterinfo.go
  pkg/bk-monitor-worker/internal/metadata/task/bcs.go
  pkg/bk-monitor-worker/service/scheduler/periodic/periodic.go
Labels: feat, datalink, bk-monitor-worker

#837 feat: collector 新增 otlogsjson 样例 --story=125075475
  pkg/collector/example/otlogsjson/go.mod
  pkg/collector/example/otlogsjson/logs.json
  pkg/collector/example/otlogsjson/main.go
  pkg/collector/go.mod
  pkg/collector/go.sum
Labels: feat, datalink

#838 feat: transfer 修复 esb/cc 路径问题 --story=125151305
  pkg/transfer/esb/cc.go
Labels: feat, datalink

#836 feat: 关联查询接口支持 info 数据类型 --story=124472659
  pkg/unify-query/cmdb/cmdb.go
  pkg/unify-query/cmdb/struct.go
  pkg/unify-query/cmdb/v1beta1/config.go
  pkg/unify-query/cmdb/v1beta1/query_maker.go
  pkg/unify-query/cmdb/v1beta1/query_maker_test.go
  pkg/unify-query/cmdb/v1beta1/struct.go
  pkg/unify-query/cmdb/v1beta1/v1beta1.go
  pkg/unify-query/cmdb/v1beta1/v1beta1_test.go
  pkg/unify-query/influxdb/router_mock.go
  pkg/unify-query/query/structured/space_test.go
  pkg/unify-query/service/http/api/api.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/victoriaMetrics/struct.go
Labels: feat, datalink

#841 feat: promql 转换多层时间聚合函数修复和 relation api 返回参数修改 --story=125242905
  pkg/unify-query/cmdb/cmdb.go
  pkg/unify-query/cmdb/struct.go
  pkg/unify-query/cmdb/v1beta1/query_maker_test.go
  pkg/unify-query/cmdb/v1beta1/v1beta1.go
  pkg/unify-query/cmdb/v1beta1/v1beta1_test.go
  pkg/unify-query/query/structured/query_promql.go
  pkg/unify-query/service/http/api/api.go
  pkg/unify-query/service/http/query_test.go
Labels: feat, datalink

#840 feat: BMW: 空间路由新增APM全局类型结果表特殊处理逻辑,实现真全局 --story=125241185
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#843 feat: 兼容 tag values 数据量过大的问题，自动路由到 label values --story=125402435
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/service/http/api.go
  pkg/unify-query/service/http/info.go
  pkg/unify-query/tsdb/victoriaMetrics/instance.go
Labels: feat, datalink

#842 feat: doris 查询 nested 数据类型适配 --story=125246589
  pkg/unify-query/internal/querystring/lex.go
  pkg/unify-query/internal/querystring/parser.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/format_test.go
  pkg/unify-query/tsdb/bksql/instance.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/bksql/sql_expr/doris.go
  pkg/unify-query/tsdb/bksql/sql_expr/doris_test.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
Labels: feat, datalink
