Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2025-08, with the labels that each got.

#915 feat: relation expand 继承数据类型修改 --story=126289349
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/module.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/set.go
  pkg/bk-monitor-worker/internal/relation/buidler.go
  pkg/bk-monitor-worker/internal/relation/builder_test.go
Labels: feat, datalink

#920 feat: 优化异常指标上报逻辑 --story=126310599
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/host.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/host_test.go
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/set.go
Labels: feat, datalink

#921 feat: vm 查询增加业务 id 返回打点 --story=126342213
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
  pkg/unify-query/tsdb/victoriaMetrics/instance.go
  pkg/unify-query/tsdb/victoriaMetrics/struct.go
Labels: feat, datalink

#922 feat: es 原始数据查询拼接问题处理，超过数据量需要返回空数据 --story=126366847
  pkg/unify-query/go.mod
  pkg/unify-query/go.sum
  pkg/unify-query/influxdb/router_mock.go
  pkg/unify-query/mock/handler.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
Labels: feat, datalink

#924 feat: 组件依赖更新 --story=126372547
  pkg/collector/go.mod
  pkg/collector/go.sum
  pkg/operator/go.mod
  pkg/operator/go.sum
Labels: feat, datalink

#916 feat: Taf 监控指标支持按维度收敛 --story=126307558
  pkg/collector/VERSION
  pkg/collector/example/example.yml
  pkg/collector/example/tars/main.go
  pkg/collector/exporter/config.go
  pkg/collector/exporter/converter/beat.go
  pkg/collector/exporter/converter/beat_test.go
  pkg/collector/exporter/converter/config.go
  pkg/collector/exporter/converter/converter.go
  pkg/collector/exporter/converter/fta.go
  pkg/collector/exporter/converter/logs.go
  pkg/collector/exporter/converter/logs_test.go
  pkg/collector/exporter/converter/metrics.go
  pkg/collector/exporter/converter/metrics_test.go
  pkg/collector/exporter/converter/pingserver.go
  pkg/collector/exporter/converter/pingserver_test.go
  pkg/collector/exporter/converter/profiles.go
  pkg/collector/exporter/converter/profiles_test.go
  pkg/collector/exporter/converter/proxy.go
  pkg/collector/exporter/converter/proxy_test.go
  pkg/collector/exporter/converter/pushgateway.go
  pkg/collector/exporter/converter/pushgateway_test.go
  pkg/collector/exporter/converter/remotewrite.go
  pkg/collector/exporter/converter/remotewrite_test.go
  pkg/collector/exporter/converter/tars.go
  pkg/collector/exporter/converter/tars_test.go
  pkg/collector/exporter/converter/traces.go
  pkg/collector/exporter/converter/traces_test.go
  pkg/collector/exporter/exporter.go
Labels: feat, collector

#933 feat: es 查询支持时间使用字符串 --story=126424888
  pkg/unify-query/internal/function/function.go
  pkg/unify-query/metadata/result_table_options.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/metadata/struct_test.go
  pkg/unify-query/mock/handler.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
Labels: feat, datalink

#938 feat: doris 查询排序异常报错处理 --story=126456144
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/bksql/sql_expr/base.go
  pkg/unify-query/tsdb/bksql/sql_expr/doris.go
Labels: feat, datalink

#944 feat: proxy 代理接口修复 handler 异常问题 --story=126602917
  pkg/unify-query/service/http/register_urls.go
Labels: feat, unify-query, datalink

#945 feat: sql 支持子查询解析 --story=126599334
  pkg/unify-query/internal/doris_parser/parser.go
  pkg/unify-query/internal/doris_parser/parser_test.go
  pkg/unify-query/internal/doris_parser/visitor.go
  pkg/unify-query/internal/json/json.go
Labels: feat, unify-query, datalink

#948 feat: 采集器自监控指标补充 --story=126629597
  pkg/bkmonitorbeat/tasks/selfstats/gather.go
Labels: feat, datalink

#954 feat: unifyquery 接口新增 is_partial 返回字段 --story=126767093
  pkg/unify-query/cmdb/v1beta1/v1beta1.go
  pkg/unify-query/service/http/handler_test.go
  pkg/unify-query/service/http/prom_data.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/instance.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/influxdb/instance.go
  pkg/unify-query/tsdb/interfaces.go
  pkg/unify-query/tsdb/offlineDataArchive/instance.go
  pkg/unify-query/tsdb/prometheus/instance.go
  pkg/unify-query/tsdb/prometheus/instance_test.go
  pkg/unify-query/tsdb/redis/instance.go
  pkg/unify-query/tsdb/victoriaMetrics/instance.go
  pkg/unify-query/tsdb/victoriaMetrics/instance_test.go
Labels: feat, datalink

#960 feat: doris 查询默认增加时间字段用于提速 --story=126912039
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/bksql/format_test.go
  pkg/unify-query/tsdb/bksql/instance_test.go
Labels: feat, unify-query, datalink

#966 feat: 优化上报异常打点 --story=126962476
  pkg/bk-monitor-worker/internal/alarm/cmdbcache/set.go
Labels: feat, datalink, bk-monitor-worker
