Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2025-07, with the labels that each got.

#844 feat: relation 查询接口忽略为空的值 --story=125424754
  pkg/unify-query/cmdb/matcher.go
Labels: feat, datalink

#846 feat: cmdb level 数据查询兼容多个 vm rt 的模式 --story=125465507
  pkg/unify-query/influxdb/router_mock.go
  pkg/unify-query/metadata/query_reference.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/interfaces.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/query/structured/space.go
  pkg/utils/router/influxdb/space.go
  pkg/utils/router/influxdb/space_gen.go
Labels: feat, datalink

#847 feat: BMW: RESULT_TABLE_DETAIL路由中新增cmdb_level_vm_rt 字段 --story=125499618
  pkg/bk-monitor-worker/internal/metadata/models/constants.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#848 feat: collector 修正 apdex service.name 获取层级 --story=125503301
  pkg/collector/VERSION
  pkg/collector/processor/apdexcalculator/factory.go
Labels: feat, datalink

#856 feat: 采集器删除弃用代码 --story=125663568
  pkg/bkmonitorbeat/tools/simulator/README.md
  pkg/bkmonitorbeat/tools/simulator/cmd/test_beat.go
  pkg/bkmonitorbeat/tools/simulator/go.mod
  pkg/bkmonitorbeat/tools/simulator/go.sum
  pkg/bkmonitorbeat/tools/simulator/internal/events/core_dump.go
  pkg/bkmonitorbeat/tools/simulator/internal/events/disk_ro.go
  pkg/bkmonitorbeat/tools/simulator/internal/events/disk_space.go
  pkg/bkmonitorbeat/tools/simulator/internal/events/events.go
  pkg/bkmonitorbeat/tools/simulator/internal/events/keyword.go
  pkg/bkmonitorbeat/tools/simulator/internal/events/oom.go
  pkg/bkmonitorbeat/tools/simulator/internal/exec/exec.go
  pkg/bkmonitorbeat/tools/simulator/internal/exec/script.go
  pkg/bkmonitorbeat/tools/simulator/internal/server/http.go
  pkg/bkmonitorbeat/tools/simulator/internal/server/icmp.go
  pkg/bkmonitorbeat/tools/simulator/internal/server/icmp_linux.go
  pkg/bkmonitorbeat/tools/simulator/internal/server/process.go
  pkg/bkmonitorbeat/tools/simulator/internal/server/prom.go
  pkg/bkmonitorbeat/tools/simulator/internal/server/server.go
  pkg/bkmonitorbeat/tools/simulator/internal/server/tcp.go
  pkg/bkmonitorbeat/tools/simulator/internal/server/udp.go
  pkg/bkmonitorbeat/tools/simulator/internal/utils/resource_limit.go
  pkg/bkmonitorbeat/tools/simulator/internal/utils/resource_limit_linux.go
  pkg/bkmonitorbeat/tools/simulator/internal/utils/resource_limit_others.go
  pkg/bkmonitorbeat/tools/simulator/test_beat.go
Labels: feat, datalink

#854 feat: collector resourcefilter 新增 default_value action --story=125572388
  pkg/collector/VERSION
  pkg/collector/example/example.yml
  pkg/collector/example/parsepprof/go.mod
  pkg/collector/example/parsepprof/go.sum
  pkg/collector/example/pyroscope/push/go.mod
  pkg/collector/example/pyroscope/push/go.sum
  pkg/collector/internal/foreach/foreach.go
  pkg/collector/processor/attributefilter/factory.go
  pkg/collector/processor/attributefilter/factory_test.go
  pkg/collector/processor/resourcefilter/config.go
  pkg/collector/processor/resourcefilter/doc.go
  pkg/collector/processor/resourcefilter/factory.go
  pkg/collector/processor/resourcefilter/factory_test.go
  pkg/collector/proxy/http_test.go
  pkg/collector/receiver/jaeger/http.go
Labels: feat, datalink

#857 feat: 采集器项目依赖升级 --story=125664742
  pkg/bk-monitor-worker/go.mod
  pkg/bk-monitor-worker/go.sum
  pkg/bk-monitor-worker/script/diff/go.mod
  pkg/bk-monitor-worker/script/diff/go.sum
  pkg/bkmonitorbeat/go.mod
  pkg/bkmonitorbeat/go.sum
  pkg/collector/go.mod
  pkg/collector/go.sum
  pkg/ingester/go.mod
  pkg/ingester/go.sum
  pkg/libgse/go.mod
  pkg/libgse/go.sum
  pkg/operator/go.mod
  pkg/operator/go.sum
  pkg/transfer/go.mod
  pkg/transfer/go.sum
Labels: feat, datalink

#858 feat: 采集器依赖版本升级 --story=125665697
  pkg/bk-log-sidecar/go.mod
  pkg/bk-log-sidecar/go.sum
  pkg/bk-log-sidecar/scripts/requirements.txt
  pkg/bkmonitorbeat/go.mod
  pkg/bkmonitorbeat/go.sum
  pkg/libgse/go.mod
  pkg/libgse/go.sum
  pkg/operator/go.mod
  pkg/operator/go.sum
  pkg/unify-query/go.mod
  pkg/unify-query/go.sum
  scripts/requirements.txt
Labels: feat, datalink

#861 feat: 组件依赖版本更新 --story=125681507
  pkg/collector/go.mod
  pkg/operator/go.mod
  pkg/operator/go.sum
  pkg/transfer/go.mod
  pkg/transfer/go.sum
  pkg/unify-query/go.mod
Labels: feat, datalink

#864 feat: 采集器构建版本调整 --story=125699527
  pkg/bkmonitorbeat/go.mod
Labels: feat, datalink

#865 feat: 修改 unifyquery 高亮判定逻辑 --story=125725398
  pkg/unify-query/go.mod
  pkg/unify-query/internal/function/highlight.go
  pkg/unify-query/internal/function/highlight_test.go
  pkg/unify-query/internal/querystring/parser_test.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
Labels: feat, datalink

#866 feat: 修改 unifyquery 高亮判定逻辑 --story=125725398
  pkg/unify-query/internal/function/highlight.go
  pkg/unify-query/service/http/query_test.go
Labels: feat, datalink

#868 fix: pyroscope-go升级到1.2.2适配golang版本升级 --bug=145246666
  pkg/bk-monitor-worker/go.mod
  pkg/bk-monitor-worker/go.sum
Labels: fix, datalink, bk-monitor-worker

#869 feat: collector proxy 自监控打点优化 --story=125762592
  pkg/bk-monitor-worker/script/diff/go.mod
  pkg/bk-monitor-worker/script/diff/go.sum
  pkg/collector/processor/attributefilter/factory_test.go
  pkg/collector/proxy/http.go
  pkg/collector/proxy/metrics.go
Labels: feat, datalink

#873 feat: BMW: APM路由需求支持,BKCI空间路由下特定结果表使用配置的filter alias作为key --story=125810031
  pkg/bk-monitor-worker/config/metadata_config.go
  pkg/bk-monitor-worker/go.sum
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#877 fix: bmw查询路由预计算刷新问题 --bug=145517839
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/task/customreport.go
Labels: fix, datalink, bk-monitor-worker

#878 feat: query ts 接口查询支持非时间对齐 --story=125878026
  pkg/unify-query/query/structured/query_promql.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/service/http/query.go
Labels: feat, datalink

#880 feat: promql 支持 now() 函数语法 --story=125892519
  pkg/unify-query/internal/function/highlight.go
  pkg/unify-query/internal/function/highlight_test.go
  pkg/unify-query/query/structured/query_promql.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
Labels: feat, datalink

#881 feat: 修复高亮重复 mark 的问题 --story=125922295
  pkg/unify-query/internal/function/highlight.go
  pkg/unify-query/internal/function/highlight_test.go
Labels: feat, datalink

#884 feat: 兼容 es 不同版本的 mapping 获取方式 --story=125971736
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
Labels: feat, datalink

#885 fix: bklog panic fix --bug=145658756
  pkg/unify-query/service/http/handler.go
Labels: fix, datalink

#886 feat: collector 支持动态调整 profiles batchsize --story=125982589
  pkg/collector/VERSION
  pkg/collector/exporter/config.go
  pkg/collector/exporter/queue/batch.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-application.conf.tpl
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-k8s-main
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
Labels: feat, datalink

#870 feat: bk-monitor-worker查询路由多租户适配 --story=125769554
  pkg/bk-monitor-worker/bmw.yaml.tpl
  pkg/bk-monitor-worker/config/config.go
  pkg/bk-monitor-worker/internal/api/client.go
  pkg/bk-monitor-worker/internal/metadata/apiservice/bkdata.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/base.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/constants.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/define.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/flow.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/node_processor.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/node_source.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/node_storage.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/task_cmdblevel.go
  pkg/bk-monitor-worker/internal/metadata/dataflow/task_filtertime.go
  pkg/bk-monitor-worker/internal/metadata/models/common.go
  pkg/bk-monitor-worker/internal/metadata/models/customreport/basic.go
  pkg/bk-monitor-worker/internal/metadata/models/customreport/event.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/accessvmrecord.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/accessvmrecord_test.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/influxdbclusterinfo.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/influxdbhostinfo.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/influxdbstorage.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/influxdbtaginfo.go
  pkg/bk-monitor-worker/internal/metadata/service/dataflow.go
  pkg/bk-monitor-worker/internal/metadata/service/datasource.go
  pkg/bk-monitor-worker/internal/metadata/service/datasource_test.go
  pkg/bk-monitor-worker/internal/metadata/service/kafkatopicinfo.go
  pkg/bk-monitor-worker/internal/metadata/service/spacedatasource.go
  pkg/bk-monitor-worker/internal/metadata/service/spacedatasource_test.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup_test.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesmetric.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesmetric_test.go
  pkg/bk-monitor-worker/internal/metadata/task/config_refresh.go
  pkg/bk-monitor-worker/internal/metadata/task/customreport.go
  pkg/bk-monitor-worker/internal/metadata/task/space.go
  pkg/bk-monitor-worker/script/diff/.gitignore
  pkg/bk-monitor-worker/script/diff/Makefile
  pkg/bk-monitor-worker/script/diff/cmd/consuldiff.go
  pkg/bk-monitor-worker/script/diff/cmd/redisdiff.go
  pkg/bk-monitor-worker/script/diff/cmd/root.go
  pkg/bk-monitor-worker/script/diff/consul/config.go
  pkg/bk-monitor-worker/script/diff/consul/config_test.go
  pkg/bk-monitor-worker/script/diff/consul/consuldiff.go
  pkg/bk-monitor-worker/script/diff/consul/consuldiff_test.go
  pkg/bk-monitor-worker/script/diff/diff.go
  pkg/bk-monitor-worker/script/diff/diff.yaml
  pkg/bk-monitor-worker/script/diff/diff.yaml.tpl
  pkg/bk-monitor-worker/script/diff/diff_test.yaml
  pkg/bk-monitor-worker/script/diff/go.mod
  pkg/bk-monitor-worker/script/diff/go.sum
  pkg/bk-monitor-worker/script/diff/redis/config.go
  pkg/bk-monitor-worker/script/diff/redis/redisdiff.go
  pkg/bk-monitor-worker/script/diff/redis/redisdiff_test.go
  pkg/bk-monitor-worker/script/diff/util/validate.go
  pkg/bk-monitor-worker/service/scheduler/periodic/periodic.go
Labels: feat, datalink, bk-monitor-worker

#887 feat: collector 主配置文件增加日志的rate_limiter
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
Labels: notapd, feat

#889 feat: operator 版本依赖固化 --story=126052050
  pkg/bkmonitorbeat/go.mod
  pkg/bkmonitorbeat/go.sum
  pkg/collector/example/parsepprof/go.mod
  pkg/collector/go.mod
  pkg/collector/go.sum
  pkg/libgse/go.mod
  pkg/libgse/go.sum
  pkg/operator/go.mod
  pkg/operator/go.sum
  pkg/utils/go.mod
Labels: feat, datalink

#895 feat: BMW: RESULT_TABLE_DETAIL路由调整,doris结果表路由 Storage Type适配 --story=126093129
  pkg/bk-monitor-worker/internal/metadata/models/constants.go
Labels: feat, datalink, bk-monitor-worker

#888 feat: libgse gseoutput 支持 flowlimiter --story=126049213
  pkg/libgse/go.mod
  pkg/libgse/go.sum
  pkg/libgse/output/gse/config.go
  pkg/libgse/output/gse/gse.go
Labels: feat, datalink

#896 feat: 采集器 proccustom 支持正则匹配 --story=126096482
  pkg/bkmonitorbeat/VERSION
  pkg/bkmonitorbeat/configs/pingconfig_test.go
  pkg/bkmonitorbeat/configs/proccustom.go
  pkg/bkmonitorbeat/configs/proccustom_test.go
Labels: feat, datalink

#897 feat: operator 支持 promsd 关联指定 dataid --story=126181707
  pkg/operator/operator/objectsref/controller.go
  pkg/operator/operator/objectsref/node.go
  pkg/operator/operator/operator.go
  pkg/operator/operator/promsd.go
Labels: feat, datalink

#901 feat: BMW: ES结果表详情路由支持日志平台虚拟RT --story=126210209
  pkg/bk-monitor-worker/internal/metadata/models/storage/esstorage.go
  pkg/bk-monitor-worker/internal/metadata/models/storage/qs_esstorage_gen.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
Labels: feat, datalink, bk-monitor-worker

#900 feat: libgse 提供 bkpush 限流器特性 --story=126207048
  pkg/libgse/common/flowlimiter.go
  pkg/libgse/output/bkpush/bkpush.go
  pkg/libgse/output/gse/config.go
  pkg/libgse/output/gse/gse.go
Labels: feat, datalink

#898 feat: 采集器支持指定 metricbeat_align_ts 参数 --story=126183560
  pkg/bkmonitorbeat/VERSION
  pkg/bkmonitorbeat/script/generate_support_files/write_project_yaml.sh
  pkg/bkmonitorbeat/script/generate_support_files/write_root_conf_tpl.sh
  pkg/bkmonitorbeat/support-files/templates/freebsd/x86_64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/freebsd/x86_64/project.yaml
  pkg/bkmonitorbeat/support-files/templates/linux/aarch64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/aarch64/project.yaml
  pkg/bkmonitorbeat/support-files/templates/linux/x86/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86/project.yaml
  pkg/bkmonitorbeat/support-files/templates/linux/x86_64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/linux/x86_64/project.yaml
  pkg/bkmonitorbeat/support-files/templates/windows/x86/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86/project.yaml
  pkg/bkmonitorbeat/support-files/templates/windows/x86_64/etc/bkmonitorbeat.conf.tpl
  pkg/bkmonitorbeat/support-files/templates/windows/x86_64/project.yaml
Labels: feat, datalink

#903 feat: BMW: 路由任务查询ResultTableField和TimeSeriesMetric时,分批参数配置化 --story=126241512
  pkg/bk-monitor-worker/config/metadata_config.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
Labels: feat, datalink, bk-monitor-worker

#905 feat: collector 配置文件完善 --story=126257571
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-k8s-main
Labels: feat, datalink

#908 feat: unifyquery 多 tsdb 检索逻辑下原始数据排序问题修改 --story=126241444
  pkg/unify-query/internal/doris_parser/parser_test.go
  pkg/unify-query/internal/doris_parser/visitor.go
  pkg/unify-query/internal/function/highlight.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
Labels: feat, datalink
