Repository TencentBlueKing/bkmonitor-datalink, pull requests merged in 2025-03, with the labels that each got.

#709 fix: 暴露 prome 指标的channel给下游处理 --bug=139059475
  pkg/libgse/beat/push.go
Labels: fix, datalink

#706 feat: 补充对 logs 数据源 attributes/resource 字段等处理逻辑
  pkg/collector/VERSION
  pkg/collector/internal/testkits/assert.go
  pkg/collector/processor/attributefilter/factory.go
  pkg/collector/processor/attributefilter/factory_test.go
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-application.conf.tpl
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-k8s-main
  pkg/collector/support-files/templates/linux/x86_64/etc/bk-collector-main.conf.tpl
Labels: notapd, feat

#707 feat: 查询支持 missing 和非秒级 --story=122197761
  .gitignore
  pkg/unify-query/cmdb/v1beta1/v1beta1.go
  pkg/unify-query/influxdb/router_mock.go
  pkg/unify-query/influxdb/spacetsdb_router_test.go
  pkg/unify-query/internal/function/function.go
  pkg/unify-query/internal/function/function_test.go
  pkg/unify-query/metadata/featureFlag.go
  pkg/unify-query/metadata/featureFlag_test.go
  pkg/unify-query/metadata/query_params.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/mock/handler.go
  pkg/unify-query/query/promql/tables.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/query/structured/space_test.go
  pkg/unify-query/service/http/api.go
  pkg/unify-query/service/http/check_handler.go
  pkg/unify-query/service/http/handler_test.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
  pkg/unify-query/tsdb/prometheus/querier.go
Labels: feat, datalink

#710 fix: 修复 es 查询 queryString 解析异常问题 --bug=139062441
  pkg/unify-query/tsdb/elasticsearch/query_string.go
  pkg/unify-query/tsdb/elasticsearch/query_string_test.go
Labels: fix, datalink

#713 feat: 新增同指标合并特性 --story=122296147
  pkg/unify-query/cmdb/v1beta1/v1beta1_test.go
  pkg/unify-query/featureFlag/featureFlag.go
  pkg/unify-query/influxdb/influxdb_router_test.go
  pkg/unify-query/metadata/queries.go
  pkg/unify-query/metadata/reference_test.go
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/promql/ctx.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/service/http/api.go
  pkg/unify-query/service/http/check_handler.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/prometheus/instance.go
  pkg/unify-query/tsdb/prometheus/merge_series.go
  pkg/unify-query/tsdb/prometheus/merge_series_test.go
  pkg/unify-query/tsdb/prometheus/querier.go
  pkg/unify-query/tsdb/victoriaMetrics/struct.go
Labels: feat, datalink

#715 feat: bksql 支持 labelvalues 查询多表 --story=122374028
  pkg/unify-query/tsdb/bksql/instance.go
Labels: feat, datalink

#716 feat: 打开 trace 全采样 --story=122386247
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/service/trace/service.go
Labels: feat, datalink

#719 feat: BMW: 调整授权给BKCI访问的BKCC RT列表获取方式，调整为可配置项 --story=122445619
  pkg/bk-monitor-worker/config/metadata_config.go
  pkg/bk-monitor-worker/internal/metadata/models/constants.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
Labels: feat, datalink, bk-monitor-worker

#701 feat: BMW: SPACE_TO_RESULT_TABLE_KEY中针对非二段式TableId，补充.__default__ --story=122006276
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis_test.go
  pkg/bk-monitor-worker/store/redis/redis.go
Labels: feat, datalink, bk-monitor-worker

#720 feat: bksql 聚合时间对齐时区问题 --story=122444004
  pkg/unify-query/query/structured/condition_field.go
  pkg/unify-query/query/structured/condition_test.go
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/bksql/format_test.go
  pkg/unify-query/tsdb/bksql/instance_test.go
Labels: feat, datalink

#721 feat: 优化 unifyquery 指标上报 --story=122473465
  pkg/unify-query/metric/metric.go
Labels: feat, datalink

#718 feat: es 非时间聚合根据时区对齐 --story=122431611
  pkg/unify-query/internal/function/function.go
  pkg/unify-query/internal/function/function_test.go
  pkg/unify-query/query/promql/engine_mock.go
  pkg/unify-query/query/structured/method.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/query/structured/timeaggregate.go
  pkg/unify-query/query/structured/window.go
  pkg/unify-query/service/http/check_handler.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/format_test.go
  pkg/unify-query/tsdb/elasticsearch/functions.go
  pkg/unify-query/tsdb/elasticsearch/functions_test.go
Labels: feat, datalink

#725 feat: Metadata: 允许业务访问自身的DBM主机数据 --story=122532874
  pkg/bk-monitor-worker/internal/metadata/models/storage/clusterinfo.go
  pkg/bk-monitor-worker/internal/metadata/service/spaceredis.go
Labels: feat, datalink

#727 feat: BMW: 指标发现支持指定白名单,只允许查询白名单指标 --story=122568417
  pkg/bk-monitor-worker/internal/metadata/models/constants.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup.go
  pkg/bk-monitor-worker/internal/metadata/service/timeseriesgroup_test.go
  pkg/bk-monitor-worker/internal/metadata/task/customreport.go
Labels: feat, datalink, bk-monitor-worker

#724 feat: es 查询支持非整数聚合以及排序顺序 --story=122522559
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/query/promql/tables.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/query_ts_test.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/bksql/format.go
  pkg/unify-query/tsdb/bksql/format_test.go
  pkg/unify-query/tsdb/bksql/instance_test.go
  pkg/unify-query/tsdb/elasticsearch/format.go
  pkg/unify-query/tsdb/elasticsearch/format_test.go
  pkg/unify-query/tsdb/elasticsearch/functions.go
  pkg/unify-query/tsdb/elasticsearch/functions_test.go
  pkg/unify-query/tsdb/elasticsearch/instance.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
Labels: feat, datalink

#726 feat: 采集器 metricbeat 采集不缓存 token 信息及 kubeevent 维度补充 --story=122562799
  pkg/bkmonitorbeat/VERSION
  pkg/bkmonitorbeat/tasks/exceptionbeat/exceptionbeat_unix.go
  pkg/bkmonitorbeat/tasks/kubeevent/event.go
  pkg/bkmonitorbeat/tasks/metricbeat/module/prometheus/collector/httpclient.go
Labels: feat, datalink

#729 feat: 查询支持order 排序 --story=122588742
  pkg/unify-query/metadata/struct.go
  pkg/unify-query/metadata/struct_test.go
  pkg/unify-query/mock/handler.go
  pkg/unify-query/query/structured/query_ts.go
  pkg/unify-query/query/structured/sort.go
  pkg/unify-query/service/http/query.go
  pkg/unify-query/service/http/query_test.go
  pkg/unify-query/tsdb/elasticsearch/instance_test.go
Labels: feat, datalink

#730 feat: 查询 TableID 路由去重 --story=122607171
  pkg/unify-query/query/structured/space.go
Labels: feat, datalink
